### ISSUE TITLE
Authentication methods not working | Bun

### ISSUE THREAD

**Issue by VLtim43** [Abdullah-Malik/spotified#42]
Trying to follow the documentation to implement this lib but can't seem to make any of the auth methods to work at all.
Setup a bun-vite environment to run the project

Authorization Code Flow and Implicit Grant Flow just says unable to connect after launching the server
Authorization Code Flow with PKCE works halfway but after clicking the accounts/spotify authorize form it also drops unable to connect

Following exactly the documentation examples and checking my redirect uri and keys on the spotify dashboard, I'm not sure if I'm doing something wrong on the redirect process

I actually would not like to use react at all and just implement the simplest auth method then using the endpoints on a terminal interface, so any suggestions on how (and best ways) to implement using the sdk are welcome too

```
import React, { useEffect, useState } from "react";
import Spotified from "spotified";

const SpotifyAuthPKCE = () => {
  const [spotified] = useState(
    new Spotified({ clientId: "<my id>" })
  );
  const [isAuthenticated, setIsAuthenticated] = useState(false);

  useEffect(() => {
    const urlParams = new URLSearchParams(window.location.search);
    const code = urlParams.get("code");
    if (code) {
      handleCallback(code);
    }
  }, []);

  const handleAuth = async () => {
    const authData =
      await spotified.auth.AuthorizationCodePKCE.generateAuthorizationURL(
        "http://localhost:3000/callback",
        {
          scope: ["user-read-private", "user-read-email"],
        }
      );
    localStorage.setItem("codeVerifier", authData.codeVerifier);
    window.location.href = authData.url;
  };

  const handleCallback = async (code) => {
    const codeVerifier = localStorage.getItem("codeVerifier");
    try {
      const tokenResponse =
        await spotified.auth.AuthorizationCodePKCE.requestAccessToken(
          code,
          codeVerifier,
          "http://localhost:3000/callback"
        );
      spotified.setBearerToken(tokenResponse.access_token);
      setIsAuthenticated(true);
    } catch (error) {
      console.error("Authentication failed:", error);
    }
  };

  return (
    <div>
      {!isAuthenticated ? (
        <button onClick={handleAuth}>Authenticate with Spotify</button>
      ) : (
        <p>Authenticated successfully!</p>
      )}
    </div>
  );
};

export default SpotifyAuthPKCE;
```

node version: v20.11.1

**Comment by Abdullah-Malik** [comment]
Thanks for letting me know. I'll add working example projects using each different auth flow in a day or two. You can refer to those. If you are still not able to make it work, then we can discuss it further.

**Comment by Abdullah-Malik** [comment]
Hey, I added node and react examples. Please take a look and let me know if it works for you

**Comment by VLtim43** [comment]
Thanks for the attention. The examples do help better understanding how setup the project!

I've been trying to implement the PKCE auth without react, however, during my tests, I find myself unable to use the "getUsersSavedTracks" endpoint. The console displays the error "Spotify API Error 400 (/tracks?limit=50&offset=0): : Missing required field: ids". Which I find a little strange since "ids" is not a parameter for this method

```
const App = () => {
  const { spotified, isAuthenticated, error, authenticate, handleCallback } =
    useSpotified("<my-id>", `${window.location.origin}/callback`, [
      "user-read-private",
      "user-read-email",
      "user-library-read",
    ]);

  useEffect(() => {
    const urlParams = new URLSearchParams(window.location.search);
    const code = urlParams.get("code");
    if (code && spotified) {
      handleCallback(code);
    }
  }, [spotified, handleCallback]);

  useEffect(() => {
    if (isAuthenticated) {
      fetchSavedData();
    }
  }, [isAuthenticated]);

  const fetchSavedData = async () => {
    if (!spotified || !isAuthenticated) {
      return;
    }

    try {
      const savedTracks: UserSavedTracks =
        await spotified.track.getUsersSavedTracks({
          limit: 50,
          offset: 0,
        });
      console.log(`Total saved tracks: ${savedTracks.total}`);
    } catch (err) {
      console.error("Error data:", err);
    }
  };
  return ( <.../> )

};

export default App;

``` 

checking the docs it specifies the request should be api.spotify.com/v1/**me**/tracks, but the code is sending api.spotify.com/v1/tracks. I'm afraid the implementation of this method in specific is not working properly. I tried manually setting spotified.get('/me/tracks') but get is unauthorized out of the scope of the lib. Could you check if this is the case please?

**Comment by Abdullah-Malik** [comment]
Yeah. I see that the method was making a request to a wrong endpoint. I fixed the issue. Please download version 1.1.3 and try again

**Comment by VLtim43** [comment]
thanks!
